#extractdata
library(data.table)
findRows<-fread("household_power_consumption.txt", header = TRUE, select = 1)
all<-(which(findRows$Date %in% c("1/2/2007", "2/2/2007")) )
skipLines<- min(all)
keepRows<- length(all)
data<- fread("household_power_consumption.txt", skip = (skipLines) , nrows = keepRows, header = TRUE)
rm(findRows)
dataNames<- names(fread("household_power_consumption.txt", nrow = 1))
setnames(data, dataNames)
data<-as.data.frame(data)
data <- within(data, datatime <- paste(data$Date, data$Time, sep = ' '))
data$datatime<-strptime(data$datatime, "%d/%m/%Y %H:%M:%S")

#plot4
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
with(data,{
        plot(data$datatime,data$Global_active_power,type="l",ylab="Global Active Power",xlab="")
        plot(data$datatime,data$Voltage,type="l",ylab="Voltage",xlab="datatime")
        plot(data$datatime, data$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
        lines(data$datatime, data$Sub_metering_2,col="red")
        lines(data$datatime, data$Sub_metering_3,col="blue")
        legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1,1),bty="n")
        plot(data$datatime,data$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="datatime")
})
dev.off()